services:
  - type: web
    name: my-fastapi-backend
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server.server:app --host 0.0.0.0 --port $PORT"
